platform :ios, '9.0'

target 'Ubud-Example' do
  use_frameworks!

  pod 'Ubud', :path => '../'

  target 'Ubud-ExampleTests' do
    inherit! :search_paths
  end

  target 'Ubud-ExampleUITests' do
    inherit! :search_paths
  end
end
